#!/usr/bin/env sh

## Change how yabai looks
    # https://github.com/koekeishiya/yabai/wiki/Configuration#layout
    # configure the global layout as "stack"
    yabai -m config layout stack
    # Override default layout for space 3 only (now space 3 will be tiled instead of stacked)
    # yabai -m config --space 3 layout bsp
    
    # https://github.com/koekeishiya/yabai/wiki/Configuration#padding-and-gaps
    yabai -m config top_padding 5
    yabai -m config bottom_padding 5
    yabai -m config left_padding 35
    yabai -m config right_padding 5
    yabai -m config window_gap 8

## ------- SPACES -------
    # yabai -m space 1 --label one
    # yabai -m space 2 --label two
    # yabai -m space 3 --label three
    # yabai -m space 4 --label four
    # yabai -m space 5 --label five
    # yabai -m space 6 --label six

## ------- RULES -------
    # https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#command-4
    # --add: Add a new rule. Rules apply to windows that spawn after said rule has been added.
    # --apply: Apply a rule to currently known windows.
    # seems like adding `yabai -m rule --apply` at the end does not work (rules are not applied to currently opened windows) but defining rules twice like below works. (see also https://github.com/koekeishiya/yabai/issues/2254#issuecomment-2102334948)
    yabai -m rule --add app="^Slack$" manage=off
    yabai -m rule --apply app="^Slack$" manage=off

    yabai -m rule --add app="^Snagit 2021$" manage=off
    yabai -m rule --apply app="^Snagit 2021$" manage=off

    yabai -m rule --add app="^System Preferences$" manage=off
    yabai -m rule --apply app="^System Preferences$" manage=off

    yabai -m rule --add app="^Logi Options$" manage=off
    yabai -m rule --apply app="^Logi Options$" manage=off

    yabai -m rule --add app="^Activity Monitor$" manage=off
    yabai -m rule --apply app="^Activity Monitor$" manage=off

    yabai -m rule --add app="^System Preferences$" manage=off
    yabai -m rule --apply app="^System Preferences$" manage=off

    yabai -m rule --add app="^Karabiner-Elements$" manage=off
    yabai -m rule --apply app="^Karabiner-Elements$" manage=off

    yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
    yabai -m rule --apply app="^Karabiner-EventViewer$" manage=off

    yabai -m rule --add app="^Disk Utility$" manage=off
    yabai -m rule --apply app="^Disk Utility$" manage=off

    yabai -m rule --add app="^Alfred Preferences$" manage=off
    yabai -m rule --apply app="^Alfred Preferences$" manage=off

    yabai -m rule --add app="^Ivanti Secure Access Client$" manage=off
    yabai -m rule --apply app="^Ivanti Secure Access Client$" manage=off

    yabai -m rule --add app="^Rancher Desktop$" manage=off
    yabai -m rule --apply app="^Rancher Desktop$" manage=off
